[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @tms/backend build"]

[start]
cmd = "node dist/index.js"
